### ISSUE TITLE
formatChildren not reusing values

### ISSUE THREAD

**Issue by aabenoja** [format-message/format-message#149]
I have a case where in the same string I want to reuse the children I specify.

```jsx
<div>
  {formatChildren(
    formatMessage('<superSpecialSpan>Tweedledee</superSpecialSpan> and <superSpecialSpan>Tweedledum</superSpecialSpan>.'),
    {
      superSpecialSpan: <SuperSpecialSpan {...superSpecialProps} />
    }
  })
</div>
```

The resulting output is `<SuperSpecialSpan {...superSpecialProps}>Tweedledee</SuperSpecialSpan> and .` It seems as though the second `superSpecialSpan` never gets rendered, as if it were getting deleted from the object once used.

**Comment by thetalecrafter** [comment]
Right now formatChildren is meant to use each child exactly once. I can see the benefit in being able to define a tag once that is used many times. The workaround for now is to use separate ones, but I can look at how difficult it would be to support this case.

**Comment by thetalecrafter** [comment]
formatChildren has been deprecated in v6.0.0. The new formatMessage.rich() api can handle reuse, though:

```
<div>
  {formatMessage.rich('<superSpecialSpan>Tweedledee</superSpecialSpan> and <superSpecialSpan>Tweedledum</superSpecialSpan>.', {
    superSpecialSpan: ({ children }) => <SuperSpecialSpan {...superSpecialProps}>{children}</SuperSpecialSpan >
  })
</div>
```
