### ISSUE TITLE
Extending format-message to support nested translations

### ISSUE THREAD

**Issue by CheloXL** [format-message/format-message#161]
I need a way to compose translations. So far, the only way for me to do so is to format a message and use that result as argument to another formatMessage. While that works, I would prefer instead to extend formatMessage adding new functionality to the existing api.

Something in the lines of `formatMessage('Current name: { name, translate }', { name: 'another_index' })`. That would imply that **another_index** needs to be translated using **formatMessage** and the result used in the original formatMessage.

I found no way to do so without changing the library on my side... Do you think something like that can be added? Is there a better/another way to do so that I'm not aware of?

Thanks!.

**Comment by thetalecrafter** [comment]
What would that look like? I'm not sure I understand the use case.

**Comment by CheloXL** [comment]
Specifically, I have a list of "names" that are translated and accessed using the normal work-flow of **formatMessage** in one place, but then I need to display that name inside another translation.

In my example above, that should be executed as: `formatMessage('Current name: { name }', { name: formatMessage('another_index') })` (this is what I actually have and want to get rid of).

**Comment by thetalecrafter** [comment]
That looks like a perfectly reasonable way to accomplish that. What alternative api would you propose?

**Comment by thetalecrafter** [comment]
Nevermind, I understand now what you were saying in your initial description. You would have a `translate` placeholder type that would take whatever string was passed in and automatically pass it to `formatMessage`.

**Comment by thetalecrafter** [comment]
I am unwilling to add any sort of extension to the ICU message format syntax. The `formatMessage` function is already composable, and I would not consider adding an indirect way to have a function called on your parameter values.

**Comment by CheloXL** [comment]
Ok. Thanks anyways!
