### ISSUE TITLE
New API for rich content handling

### ISSUE THREAD

**Issue by thetalecrafter** [format-message/format-message#167]
## Goals
* Cover current use cases for `formatChildren`
* Agnostic of the JSX pragma, preferably even of whether or not it's vdom
* Impervious to #166. Perhaps translations can still cause errors, but not runtime placeholder values
* Easy to use without babel transform
* Strong linting to catch bad tag syntax and missing tags

**Comment by thetalecrafter** [comment]
### rich 1
```jsx
formatMessage.rich('Drag & drop {filetype} file here, or <a>browse</a>.', {
  filetype: '.csv',
  a: children => <Button><FolderIcon />{children}</Button>
})
```
returns:
```jsx
[ 'Drag & drop .csv file here, or ', <Button><FolderIcon />browse</Button> ]
```
I doubt TypeScript or Flow could strongly check argument matching, but this could still be helpful:
```ts
type Child = string | Object
type FormatRich: (
  string | { default: string, id?: string, description?: string },
  { [string]: number | string | (Child[]) => Child }
) => Child[]
```
I'd expect the eslint plugin to handle parsing the message to determine expected argument types.

**Comment by thetalecrafter** [comment]
#### Prior art:
`formatChildren` formats message, then parses for xml-like tags. It is not framework agnostic, but has React & Inferno implementations. The JSX transform can't use namespaces, explicit ids, or helpful descriptions. #97 #127 #149 #166

[react-intl](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage) discourages html tags in the translatable message, but doesn't seem to cover the case where some of the tag content is translatable & should be part of the same message to retain context.

[fluent](https://github.com/projectfluent/fluent.js/wiki/React-Overlays) handles rich content with overlays, but appears to require an web environment. It uses a framework specific React component.

**Comment by thetalecrafter** [comment]
### rich 2
```
formatMessage.rich('Drag & drop {filetype} file here, or {button, element, {browse}}.', {
  filetype: '.csv',
  button: children => <Button><FolderIcon />{children}</Button>
})
```
Introduce an `element` placeholder type rather than using xml/html notation. This requires changes to both parser & interpreter (so does 1), and introduces ICU incompatibility.

### rich 3
```
formatMessage.rich('Drag & drop {filetype} file here, or {button, select, other {browse}}.', {
  filetype: '.csv',
  button: children => <Button><FolderIcon />{children}</Button>
})
```
Overload `select` placeholder type instead of introducing `element`. This requires no changes to the parser, just the interpreter, and can still make some kind of sense to other ICU implementations.

### variant A
```
formatMessage('Drag & drop {filetype} file here, or <a>browse</a>.', {
  filetype: '.csv',
  a: children => <Button><FolderIcon />{children}</Button>
})
```
Overload the existing `formatMessage` function to detect rich-ness (either tag presence, element placeholder presence, or function parameters) automatically.

## variant B
```
formatMessage({ default: 'Drag & drop {filetype} file here, or <a>browse</a>.', rich: true }, {
  filetype: '.csv',
  a: children => <Button><FolderIcon />{children}</Button>
})
```
Overload `formatMessage`, but allow a `rich` property to the first argument (when an object) to trigger returning an array instead of assuming string concatenation.

**Comment by thetalecrafter** [comment]
Please to provide feedback: @aaronshaf @bjohn465 @cameronsutter @straker @shichongrui and feel free to invite more people to weigh in.

**Comment by bjohn465** [comment]
I'm a fan of the "rich 1" option. I don't like the "rich 2" option because of the ICU incompatibility. The "rich 3" option is slightly better since it isn't ICU incompatible, but it still feels not right.

Of the two variants, I like the explicitness of "variant B" rather than the inference in "variant A."

**Comment by thetalecrafter** [comment]
Done in v6.0.0.
