### ISSUE TITLE
Custom Format Support

### ISSUE THREAD

**Issue by aabenoja** [format-message/format-message#20]
I have a use case for custom number formats. Perhaps a `customFormats` config option?

```js
formatMessage.setup({
  customFormats: {
    number: {
      'my-currency-override': { /* settings */ }
    }
  }
});
```

```js
formatMessage.setup = function(opt) {
  if (opt.customFormats) {
    if (opts.customFormats.number) {
      number = {...number, ...opts.customFormats.number};
    }
  }
};
```

**Comment by thetalecrafter** [comment]
This is a pretty cool idea.

For now, as a workaround, you can pass a pre-formatted number into your messages using [`Number.prototype.toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) or [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)

**Comment by aabenoja** [comment]
I tried my hand at it with #21. I'm also trying to come up with a good solution for getting this to work with the babel plugin options.
