### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by Yogu** [format-message/format-message#205]
I tried to convert the flow types of some packages to TypeScript, so that TypeScript projects can use this library in a type-safe manner. I can already use them in my project, but it would be good to have them published. There are two options:

- I can publish them on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) where they can be updated independently of this package
- You can add `.d.ts` files to the packages and update them when the API changes.

It would be really great to have the typings in this package because it makes it easier to use and keep track of the versions, but then they should be updated when you change APIs. @vanwagonet would that be an option? Otherwise, I'm going to publish them on DefinitelyTyped.

I put the types in a [gist](https://gist.github.com/Yogu/f3ed40d2d6fb3e4ad0b2b76983536053) in case someone wants to use / review them earlier.

**Comment by vanwagonet** [comment]
I don't use TypeScript much, but I think it makes good sense to have the type declarations in this repo, so they can easily stay up to date. I would love a pull request that adds them.

**Comment by Yogu** [comment]
Thanks, also for the quick release 🎉

**Comment by vanwagonet** [comment]
Thank you for contributing.
