### ISSUE TITLE
Allow ISO 8601 Strings for date formatting

### ISSUE THREAD

**Issue by JonathanIlk** [format-message/format-message#217]
It would be nice if the "date" and "time" formatters could also work with ISO 8601 Strings instead of only Date Objects.

This should be relatively straight-forward, since the Date Constructor also allows ISO 8601 Strings as parameter.

Example: 

`Current Date {val, date}` works with input `{val: '2018-09-13T13:11:00Z'}`

**Comment by vanwagonet** [comment]
Thanks for the suggestion. The underlying API technically only operates on numbers `Intl.DateTimeFormat().format(<number>)`, but `new Date().valueOf()` returns a number with the same meaning as the numbers it expects, so dates "just work" for free.

I'd prefer the format message api remain pretty close to the underlying formatters, and as you said, it's pretty trivial to convert your ISO strings to dates before passing them in.
