### ISSUE TITLE
parse message with single quotation mark will not work as expected

### ISSUE THREAD

**Issue by JackZong** [format-message/format-message#319]
How to reproduce:

format a message with a single quotation mark
just like the message "hello '{world}", and you can see from the below screenshot. it will not work well
![image](https://user-images.githubusercontent.com/12573233/112442921-502a8f80-8d87-11eb-8cb4-f3c07f1fffa1.png)

expected result:
message  "hello '{world}" should be parsed into message "hello 'jack"

**Comment by vanwagonet** [comment]
`'` is the [escape character in ICU MessageFormat syntax](https://unicode-org.github.io/icu/userguide/format_parse/messages/#quotingescaping). You will need to have 2 of them if you would like it to be in the actual message.

`"hello ''{world}"`
