### ISSUE TITLE
logo.svg is truncated

### ISSUE THREAD

**Issue by Guria** [format-message/format-message#32]
last char of logo doesn't fit an image

**Comment by thetalecrafter** [comment]
Hmm, that probably a missing font. It should be using `Source Sans Pro`, optionally pulling it from google fonts if you don't have it locally.

What browser & OS are you seeing this problem on?

**Comment by Guria** [comment]
Chrome Version 51.0.2704.84 (64-bit) @ Ubuntu 16.04
Just tried on Firefox and it has 2 letters truncated.

I think font worth to be translated into pathes, to avoid truncations.

**Comment by thetalecrafter** [comment]
Good plan. Will do.

**Comment by Guria** [comment]
@thetalecrafter other repos still used truncated logo
