### ISSUE TITLE
Is the "other" section in select statements meant to be required?

### ISSUE THREAD

**Issue by Xetera** [format-message/format-message#320]
I'm running into an issue where translation services like Crowdin do not support messages that don't include an `other` branch in `select` statements but I'm having a hard time finding where that requirement is mentioned in the spec (or I suppose having a hard time finding any spec for ICU syntax at all).

https://github.com/format-message/format-message/blob/df33c34d8b6078a394a451c62e153c2c7fa51829/packages/format-message-parse/__tests__/index.spec.js#L464-L467

I do not know if Crowdin uses this repo in specific but I suspect they do because their support linked me to [your repo's demo](https://format-message.github.io/icu-message-format-for-translators/editor.html) when I asked them about this problem which is why I'm asking here.

Other parsers like the one used by [this demo](https://devpal.co/icu-message-editor/) and [this parser](https://www.npmjs.com/package/@formatjs/icu-messageformat-parser) don't seem to have any problem with a missing `other` branch. I'm really not sure where the source of this behavior comes from.

For context, I'm working on a tool that can extract branches and variables inside ICU messages like this one
```json
{
  "new-entities": "New {entity, select, user {Users} bot {Bots}"
}
```
to provide static typing in a generated typescript file like
```ts
interface TranslationArguments {
  entity: "user" | "bot";
}
```
My idea here was to check for the existence of an `other` branch to decide whether or not the types should be compiled to the example above, or the more permissive
```ts
interface TranslationArguments {
  entity: "user" | "bot" | string;
}
```
when an `other` branch exists.

**Comment by vanwagonet** [comment]
`MessageFormat` was original created by ICU, and they have implementations in C & Java. When creating this implementation I tried to follow the original implementations in what is valid or not. The `select` format is implemented in Java though another class [`SelectFormat`](https://unicode-org.github.io/icu-docs/apidoc/released/icu4j/com/ibm/icu/text/SelectFormat.html). The docs there include this statement:

> You always have to define a phrase for the default keyword other; this phrase is returned when the keyword provided to the format method matches no other keyword. If a pattern does not provide a phrase for other, the method it's provided to returns the error U_DEFAULT_KEYWORD_MISSING.

From a parsing perspective, it would be easy to drop the requirement. From a formatting perspective, a non-matching value could default to an empty string. However, that would allow you to create non-portable messages. Such messages would cause errors in the official implementations of ICU MessageFormat.

**Comment by vanwagonet** [comment]
The [C++](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1SelectFormat.html) docs include the same requirement.

**Comment by Xetera** [comment]
Interesting, I had a really hard time finding resources on this so I really appreciate the link.

This seems like an arbitrarily limiting decision when thinking in terms of language design, especially for doing exhaustive checks like I am but I can see how not having any block to match might cause issues with formatting if the default behavior isn't defined.

Thanks a lot for the quick reply, I guess I'll have to stick with leaving the messages with an empty `other {}` block like

`"New {entity, select, user {Users} bot {Bots} other {}}"`
