### ISSUE TITLE
Allow for nested objects as data/keys

### ISSUE THREAD

**Issue by minimalmonkey** [format-message/format-message#57]
Firstly, thanks so much for this lib. It's really useful for a project I'm currently working on and the code is really easy to follow. Awesome work! 🙌 

For my project I'm using nested data objects that I pass to the `format` method. Right now I have to flatten the object for it to work, for example this:

```
var data = {
  'user': 'Steve',
  'members': {
    'count': 10
  }
};
```

becomes:

```
var data = {
  'user': 'Steve',
  'members.count': 10
};
```

This works fine but when the data object is huge, with lots of nested data we don't care about, it becomes a bit of a performance issue.

A work around for this would be to update the `interpretSimple` function to be:

```
function interpretSimple (id) {
  return function format (args) {
    var parts = id.split('.');
    if (parts.length > 1) {
      var i = 0;
      var l = parts.length;
      var a = args;
      for (i; i < l; i++) {
        a = a[parts[i]];
        if (!a) return '' + args[id];
      }
      return '' + a;
    }
    return '' + args[id];
  }
}
```

This would look for nested variables in an object but would fallback to how things currently work, so would be a minor update / backwards compatible.

Is this something that could be consider? If yes I can put together a PR today along with updated unit tests etc.

**Comment by minimalmonkey** [comment]
Sorry should mention for anyone else who might be interested / follow along, I'm referring to the [format-message-interpret](https://github.com/format-message/format-message/tree/master/packages/format-message-interpret) package here. 😺

**Comment by thetalecrafter** [comment]
We should definitely support that! I'd love a PR.

It's probably more complicated than just an update to interpret, though. We'd want it to be supported everywhere. A PR wouldn't need to cover every case, but I'd want them all covered before releasing.

**Comment by minimalmonkey** [comment]
Great I'll start looking into it and should hopefully have some PRs for you soon! Thanks for the quick response 😃

**Comment by minimalmonkey** [comment]
I've started work on this [here](https://github.com/format-message/format-message/compare/master...minimalmonkey:master).

When you say to have it be supported everywhere, do you mean other packages in this repo? Can you point me in the direction of where I should test to see we've got everything covered. Thanks again.

**Comment by thetalecrafter** [comment]
`interpret` will cover messages that are parsed and interpreted at runtime, but we'd also want it to work if the message was transformed at build-time, so the `babel-plugin-transform` package would need some changes. The linter would need to be able to recognize when you passed in a literal with nested properties for dotted placeholders, so `eslint-plugin` would need to be updated too.

Those both use `estree-util` which might get some of the changes.

Since `cli` just uses the other plugins, it likely needs no changes.

**Comment by minimalmonkey** [comment]
Awesome, thanks for the direction. Will take a look at this before making a PR.

**Comment by zdfs** [comment]
Hi! We're working on a PR for the nested object support and we _think_ we have the ESLint stuff figured out, but we're having difficulty with the Babel part. If we opened up a PR without the Babel support, could you help us out with it?

**Comment by thetalecrafter** [comment]
absolutely.

**Comment by thetalecrafter** [comment]
#78 got us most of the way there. I'll take a look at finishing up the babel portion this week.

**Comment by zdfs** [comment]
Thank you so much, Andy. This really helps us a lot.
