### ISSUE TITLE
Deprecate old NPM packages

### ISSUE THREAD

**Issue by maxkoryukov** [format-message/format-message#60]
Hello!

Could you remove or deprecate old package [message-format](https://www.npmjs.com/package/message-format) from NPM ??

There are a lot of packages `format-message-XXX` and `message-format-XXX`, and it is hard to determine, which is actual (for newbie like me).

P.S.: As I understood, the [format-message](https://www.npmjs.com/package/format-message) is the right package, yes?

**Comment by thetalecrafter** [comment]
They expose different APIs. Both `format-message` and `message-format` share functionality from the various other packages: `format-message-parse`, `format-message-formats`, etc.

If you are looking for a prollyfill for `Intl.MessageFormat`, then `message-format` is for you.

If you are looking for a more complete solution for translating, then `format-message` is the right package.

The only package that is no longer used in the latest versions is `format-message-babel-util`.

**Comment by maxkoryukov** [comment]
Wow... thanks..
