### ISSUE TITLE
How to use custom datetime format in strings?

### ISSUE THREAD

**Issue by maxkoryukov** [format-message/format-message#61]
Hello!

I have an ICU-string with ISO8601 format instruction for date:

`Hello, {username}, it is {ts, date} (ISO-timestamp  is {ts, date, YYYY-MM-DDThh:mm:ssZ})`

And I want to get the ISO8601-formatted date in the resulting string (`Hello, Barack Obama, it is Oct 25, 2016 (ISO-timestamp is 2016-10-25T01:01:15Z`).

ICU describes the [SimpleDateFormat](http://userguide.icu-project.org/formatparse/datetime#TOC-SimpleDateFormat), but seems, like this feature is not implemented.

More details on [stackoverflow](http://stackoverflow.com/q/40230467/1115187)

**Comment by thetalecrafter** [comment]
SimpleDateFormat is not part of format-message unfortunately. Given its complexity, I doubt we'd implement it here in the future. Alternatively, you can define a custom format using the Intl.DateTimeFormat options, or simply pass in a pre-formatted string.

In this case:
```js
formatMessage('Hello, {username}, it is {ts, date} (ISO-timestamp is {tsiso})', {
  username: 'Me',
  ts: date,
  tsiso: date.toISOString()
})
```

**Comment by vanwagonet** [comment]
6.0 supports something [similar](https://github.com/format-message/format-message/blob/master/packages/format-message-formats/__tests__/index.spec.js#L89) to SimpleDateFormat. If the style name doesn't match a format you have defined, it will try to parse it into options for Intl.DateTimeFormat.
