### ISSUE TITLE
Question: Get message in multiple languages

### ISSUE THREAD

**Issue by vizo** [format-message/format-message#62]
Hi,
first of all this module looks awesome.
I wonder if there is option to get translation of message in multiple languages on the fly? Like passing locale as option or something ...

**Comment by thetalecrafter** [comment]
You can set it up to do multiple languages on the fly.

You'll want to call `formatMessage` with the [locale parameter](https://github.com/format-message/format-message/tree/master/packages/format-message#formatmessagepattern-args-locales).

And you'd need to make sure when you [setup()](https://github.com/format-message/format-message/tree/master/packages/format-message#formatmessagesetupoptions), you've given all of the`translations` you'll need.

**Comment by vizo** [comment]
Thank you for your help! ;)
