### ISSUE TITLE
Date and number formatting.

### ISSUE THREAD

**Issue by zdfs** [format-message/format-message#68]
It seems like the following syntaxes should work:

`{valid_to_date, date, MMMM}` or `{valid_to_date, date, yyyy}` etc
`{day, ordinal}`

The ICU editor doesn't seem to do anything with the ordinal. And date formats only seem to support `short`, `medium`, or `long`. 

Help?

**Comment by zdfs** [comment]
I found your documentation on why `ordinal` doesn't work. But how about the date formats? Possible?

**Comment by thetalecrafter** [comment]
The date formats are certainly possible, but currently you need to [setup](https://github.com/format-message/format-message/tree/master/packages/format-message#formatmessagesetupoptions) a named style with [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) options.

Specifying a specific pattern is usually pretty locale-specific. For example: `M/d/y` is commonly used in en-US, but would be very confusing in en-GB.

We could put together a package that takes a pattern and converts it to DateTimeFormat options, so the final formatting would be amenable to the locale, but might be quite different from the pattern. Is that something you'd be interested in?

**Comment by zdfs** [comment]
Maybe? I'm interested in being able to take a date object and returning a specific part of it in a specific format (like PHP). This would help me since the ICU syntax supported here is not really as flexible as the ICU spec.

**Comment by thetalecrafter** [comment]
so if you had `M/d/yyyy`, you would want it to always format exactly that way regardless of locale? Or try to do a closest match?

**Comment by zdfs** [comment]
I'm thinking more of the use case like `{valid_to_date, date, yyyy}` where I only want one part of the date. Seems like if I want a full date object, what you have works.

**Comment by thetalecrafter** [comment]
That makes sense. In that use case either way should work. I'll add this to future enhancements.

**Comment by thetalecrafter** [comment]
I'm working on support for this right now in the `next` branch. [source](https://github.com/format-message/format-message/blob/next/packages/format-message-formats/index.js#L137) [test](https://github.com/format-message/format-message/blob/next/packages/format-message-formats/__tests__/index.spec.js#L89)

One caveat though, is that while I'm creating options for `Intl.DateTimeFormat` that only include the parts you care about, it's still possible for the formatted string to include additional pieces. `AM/PM` being a likely example.

Does this look like it will work for you when released, or do you have any suggestions?

**Comment by thetalecrafter** [comment]
This functionality is now in v6.0.0.
