### ISSUE TITLE
Date formatting bug

### ISSUE THREAD

**Issue by zdfs** [format-message/format-message#69]
I've seen this bug on both the ICU editor and in my local dev environment.

![screen shot 2016-12-15 at 2 40 10 pm](https://cloud.githubusercontent.com/assets/619628/21245004/173abcda-c2d5-11e6-998e-5d0de0d597c9.png)
---
![screen shot 2016-12-15 at 2 44 17 pm](https://cloud.githubusercontent.com/assets/619628/21245005/18f28f8a-c2d5-11e6-98c7-01b409a6d63c.png)

I'm not exactly sure how it happens. I just start messing with the day/month values and it eventually becomes inconsistent.

**Comment by thetalecrafter** [comment]
On the surface it seems to me like it could be a timezone issue. Since you are putting in a string date, the browser may be parsing it as UTC, and then displaying in local time. Or vice versa.

Is it always just off by 1 day?

**Comment by zdfs** [comment]
Sorry about the delay on this...it starts off correctly and then eventually gets out of sync when I start playing with the datepicker itself.

**Comment by thetalecrafter** [comment]
Moved issue to format-message/icu-message-format-for-translators#4
