### ISSUE TITLE
JSX Bug ?

### ISSUE THREAD

**Issue by flessard** [format-message/format-message#86]
I try this in my react app 
  
```
            <p className="c-alerts__text">
              {formatChildren(
                formatMessage("You have {maxDashbaords, number} dashboards. Please __upgrade__ to add more.", {
                  maxDashbaords
                }),
                {
                  __: <a href="/Plans" />,
                }
              )}
            </p>
```

but i got` YOU HAVE ONLY 1 DASHBOARDS LEFT __UPGRADE__ YOUR PLAN NOW!`

**Comment by thetalecrafter** [comment]
If you are using `babel-transform-format-message`, then you can just use `translate="yes"` instead of directly needing to use `formatChildren`.

```
<p className="c-alerts__text" translate="yes">
  You have {formatMessage.number(maxDashboards)} dashboards.
  Please <a href="/Plans">upgrade</a> to add more.
</p>
```

If not, the api is actually wrong in the README. :oops: It should be using xmlish tokens:

```
<p className="c-alerts__text">
  {formatChildren(
    formatMessage("You have {maxDashbaords, number} dashboards. Please <0>upgrade</0> to add more.", {
      maxDashbaords
    }),
    [
      <a href="/Plans" />
    ]
  )}
</p>
```

**Comment by flessard** [comment]
Nice, can you force id whit `babel-transform-format-message`. Like <div translate="yes" translateId="id">  ?

**Comment by flessard** [comment]
@thetalecrafter btw, you need to add key props on a array of components. otherwise react rise a Warning : https://fb.me/react-warning-keys.

```
<p className="c-alerts__text">
  {formatChildren(
    formatMessage("<1>You have {maxDashbaords, number} dashboards. Please <0>upgrade</0> to add more.<1>", {
      maxDashbaords
    }),
    [
      <a key={0} href="/Plans" />,
      <p key={1} />
    ]
  )}
</p>
```

**Comment by flessard** [comment]
@thetalecrafter did you plan to fix Warning : https://fb.me/react-warning-keys i go this error after  `babel-transform-format-message`

**Comment by thetalecrafter** [comment]
As a workaround for now, you can add your own keys in those cases. Yes, let's fix it so you don't have to.
