### ISSUE TITLE
JSX translate force id

### ISSUE THREAD

**Issue by flessard** [format-message/format-message#93]
There is a way to force the id of translate when you use JSX translate="yes".

Like:
`<p translate="yes" translateId="test">Test</p>`

**Comment by thetalecrafter** [comment]
I think that could be good. If you're up for submitting a PR yourself, that would definitely get the change in quicker.

**Comment by thetalecrafter** [comment]
If you need to be able to set an explicit id for a rich message, please use the new formatMessage.rich available in v6.0.0
